### ISSUE TITLE
個人用ウェブページへのリンクを可能にする

### ISSUE THREAD

**Issue by hajifkd** [UTokyo-HEP-Theory/www-hep#1]
個人のページへのリンクがある人がいるので、`"webpage"`のようなフィールドをJSONに入れる必要がありそう。

**Comment by kantohm11** [comment]
https://github.com/kantohm11/www-hep/commit/711c1c2de4e02aeedbcbae78809d6285a7d1c814

website 列を作ることも考えたけどリンクを貼りたい人があまりいないと思うので名前の後にくっつける方式でどうでしょう。

**Comment by hajifkd** [comment]
うごいてますね、ありがとうございます。
