### ISSUE TITLE
スマホ版の名簿のデザイン？

### ISSUE THREAD

**Issue by hajifkd** [UTokyo-HEP-Theory/www-hep#7]
スマホで見ると少し名簿のデザインがきつきつ。
とはいえ特に改善案はないのですが…。
開き直って縦書きにするのもありか。

![image](https://github.com/user-attachments/assets/3c08afa2-800b-4779-b7a9-80b319b388d3)

**Comment by kantohm11** [comment]
commit 83807da 
min-width: 500px;
overflow-x: scroll 
にしてみました。
